### ISSUE TITLE
No module named flask_restplus

### ISSUE THREAD

**Issue by konraifen88** [bk1285/rpi_wordclock#148]
When trying to start the project on a clean RPI I've got the following stacktrace:

```
Traceback (most recent call last):
  File "/home/pi/rpi_wordclock/wordclock.py", line 10, in <module>
    import wordclock_interfaces.web_interface as wciweb
  File "/home/pi/rpi_wordclock/wordclock_interfaces/web_interface.py", line 3, in <module>
    from flask_restplus import Api, Resource, fields
ImportError: No module named flask_restplus
```

After I've installed the _flask_restplus_ module using pip the project started as expected.

**Comment by bk1285** [comment]
Thank you for reporting, @konraifen88 

I'll update the docs.
