### ISSUE TITLE
module 'wiring' has no attribute 'wiring'

### ISSUE THREAD

**Issue by Viszje** [bk1285/rpi_wordclock#198]
Troughout the proces in wordclock.py received error; 

Traceback (most recent call last):
  File "wordclock.py", line 196, in <module>
    word_clock = wordclock()
  File "wordclock.py", line 65, in __init__
    self.wcd = wcd.wordclock_display(self.config, self.wci)
  File "/home/pi/rpi_wordclock-master/wordclock_tools/wordclock_display.py", line 38, in __init__
    self.wcl = wiring.wiring(config)
AttributeError: module 'wiring' has no attribute 'wiring'

wordclock_display.py is pointing towards;
    Initialization
        """
        # Get the wordclocks wiring-layout
        self.wcl = wiring.wiring(config)

> Files as following in directory; 
![image](https://user-images.githubusercontent.com/88449522/128215475-befb6ca0-95e7-4658-8ecd-6e168b79c14c.png)

Can anyone point me in de right direction?
Already did try; 
https://github.com/bk1285/rpi_wordclock/pull/175

**Comment by Viszje** [comment]
Solved > 
import wordclock_tools.writing as writing did the trick
