### ISSUE TITLE
Possible Code errors py3 development version

### ISSUE THREAD

**Issue by R0lleston** [bk1285/rpi_wordclock#200]
@bk1285 this screen dump is from over the weekend (so you may have made changes to the code since then).
From the development code when I run wordclock the below issues occur. Note please ignore the pyapi - as I didnt install it.

Plugins that werent working are:
1) the sun rise / set (via Astral) - i did eventually get V2.2 loaded with some hassle. So unsure why the below errors occur
2) snake
3) RSS feeds

if it helps I'm running strech lite, with python 3.8 installed

pi@wordclock:~/rpi_wordclock $ sudo python3 wordclock.py
2021-08-09 20:51:10 wordclock root[618] INFO Software version: v1.0.0-dev-74-gc62cad3
2021-08-09 20:51:10 wordclock root[618] INFO Parsing /home/pi/rpi_wordclock/wordclock_config/wordclock_config.cfg
2021-08-09 20:51:11 wordclock root[618] INFO Interface type set to gpio_low
2021-08-09 20:51:11 wordclock root[618] INFO Wiring configuration
2021-08-09 20:51:11 wordclock root[618] INFO   WCA_WIDTH: 11
2021-08-09 20:51:11 wordclock root[618] INFO   WCA_HEIGHT: 10
2021-08-09 20:51:11 wordclock root[618] INFO   Num of LEDs: 114
2021-08-09 20:51:11 wordclock root[618] INFO   Wiring layout: bernds_wiring
2021-08-09 20:51:11 wordclock root[618] INFO Setting language to english.
2021-08-09 20:51:11 wordclock root[618] WARNING Failed to import plugin sunrise!
Traceback (most recent call last):
  File "wordclock.py", line 107, in __init__
    self.plugins.append(import_module('wordclock_plugins.' + plugin + '.plugin').plugin(self.config))
ImportError: No module named 'astral'

2021-08-09 20:51:11 wordclock root[618] INFO Selected "time_default" as default plugin
2021-08-09 20:51:11 wordclock root[618] INFO Imported plugin 0: "time_default".
2021-08-09 20:51:11 wordclock root[618] INFO Imported plugin 1: "time_matrix".
2021-08-09 20:51:11 wordclock root[618] INFO Imported plugin 2: "time_in_seconds".
2021-08-09 20:51:12 wordclock root[618] WARNING Failed to import plugin feed_parser!
Traceback (most recent call last):
  File "wordclock.py", line 107, in __init__
    self.plugins.append(import_module('wordclock_plugins.' + plugin + '.plugin').plugin(self.config))
  File "/usr/local/lib/python3.5/dist-packages/feedparser/http.py", line 156
    new_pieces[1] = f'{url_pieces.hostname}:{url_pieces.port}'
                                                           ^
SyntaxError: invalid syntax

2021-08-09 20:51:12 wordclock root[618] INFO Imported plugin 3: "restart".
2021-08-09 20:51:12 wordclock root[618] INFO Imported plugin 4: "leds_off".
2021-08-09 20:51:12 wordclock root[618] INFO Skipping plugin time_as_words_dutch since it is set to activate=false in the config-file.
2021-08-09 20:51:12 wordclock root[618] INFO Imported plugin 5: "matrix".
2021-08-09 20:51:12 wordclock root[618] INFO Imported plugin 6: "rainbow".
2021-08-09 20:51:12 wordclock root[618] WARNING Failed to import plugin weather_forecast!
Traceback (most recent call last):
  File "wordclock.py", line 107, in __init__
    self.plugins.append(import_module('wordclock_plugins.' + plugin + '.plugin').plugin(self.config))
ImportError: No module named 'pywapi'

2021-08-09 20:51:12 wordclock root[618] INFO Imported plugin 7: "ip_address".
2021-08-09 20:51:12 wordclock root[618] INFO Imported plugin 8: "shutdown".
2021-08-09 20:51:12 wordclock root[618] INFO Imported plugin 9: "time_as_words_german".
2021-08-09 20:51:12 wordclock root[618] WARNING Failed to import plugin snake!
Traceback (most recent call last):
  File "wordclock.py", line 107, in __init__
    self.plugins.append(import_module('wordclock_plugins.' + plugin + '.plugin').plugin(self.config))
ImportError: No module named 'Snakeobject'

2021-08-09 20:51:12 wordclock root[618] INFO Imported plugin 10: "tetris".
 * Serving Flask app "wordclock_interfaces.web_interface" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
2021-08-09 20:51:12 wordclock werkzeug[618] INFO  * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
2021-08-09 20:51:22 wordclock root[618] INFO Running plugin time_default.

**Comment by R0lleston** [comment]
Seems to work fine with @phenze version running on stock buster. Suspect it was an issue with using stretch and py3.8
